name: build flannel

on:
  push:
    branches: [ master ]

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout che-machine-exec source code
      uses: actions/checkout@v2
    - name: Login to quay.io
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}
        registry: quay.io
    - name: Build and push both short SHA tag and next tag
      run: |
        make flannel-git
